seed: 2025
data_name: yelp2018
data_dir: datasets/
use_attention: 1
use_pretrain: 1
pretrain_embedding_dir: datasets/
pretrain_model_path: trained_model/model.pth
save_dir : trained_model/KGRec/yelp2018/
cf_batch_size: 1024
kg_batch_size: 2048
test_batch_size: 2048
embed_dim: 64
relation_dim: 64
laplacian_type: random-walk
aggregation_type: gcn
conv_dim_list: '[64, 32, 16]'
mess_dropout: '[0.1, 0.1, 0.1]'
kg_l2loss_lambda: 0.00001
cf_l2loss_lambda: 0.00001
lr: 0.0001
n_epoch: 50
stopping_steps: 10
cf_print_every: 10
kg_print_every: 10
evaluate_every: 5
Ks: '[20, 40, 60, 80, 100]'
